site_name: "Optimized Video Analytics for IoT: from Edge to Cloud"
nav:
  - Home: index.md
  - Projects: projects.md
  - Impacts: impacts.md
  - Educational Activities: educational_activities.md
  - Personnel: personnel.md
  - Collaborators: collaborators.md
theme:
  name: material
  palette:
    - scheme: default
      primary: "red"
      accent: "red"
  navigation_depth: 2
