site_name: "Cross-Layer Design of Video Analytics for the Internet of Things"
nav:
  - Home: index.md
  - Selected Projects: selected_projects.md
  - Impacts: impacts.md
  - Educational Activities: educational_activities.md
  - Personnel: personnel.md
  - Collaborators: collaborators.md
theme:
  name: material
  palette:
    - scheme: default
      primary: "red"
      accent: "red"
  navigation_depth: 2
